events {}

http {
    upstream spring-server {
        server spring-app:8080;  # Spring Boot 컨테이너
    }

    # HTTP 요청을 ALB에서 받은 후 처리
    server {
        listen 80;

        location / {
            proxy_pass http://spring-server;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}